### ISSUE TITLE
SwarmSpawner.image_whitelist spawn only default image

### ISSUE THREAD

**Issue by zi-dan** [jupyterhub/dockerspawner#285] opened 2019-02-15 10:15 UTC
Hi Guys,

I try to use image_whitelist in my SwarmSpawner with guidance of issue #219  but always a default image is choosen. It looks like a image_whitelist options are skipped and always values of SwarmSpawner.image is taken from configuration. 
My jupyter_config has following parameters:

```
c.JupyterHub.spawner_class = 'dockerspawner.SwarmSpawner' 
c.SwarmSpawner.image = 'jupyter/minimal-notebook:77e10160c7ef' 
c.SwarmSpawner.image_whitelist = { 
    'Jupyteo All-In-One': 'jupytepide/user-spawn-notebook:dev', 
    'Jupyteo EO Processing': 'jupytepide/eodata-notebook:1.3.6' 
}
```
With this config list with option is displayed but choosing any of the item loads jupyter/minimal-notebook.

Did I miss something?

**Comment by minrk** [comment] 2019-03-01 13:08
were you using dockerspawner master? This isn't in a release yet, though I'm trying to make the 0.11 release today.

**Comment by zi-dan** [comment] 2019-03-01 13:48
Yes, I use a master branch. So I will wait for update and new release.

**Comment by mathematicalmichael** [comment] 2020-07-08 19:41
hi, I cloned off master (`pip install git+https://github.com/jupyterhub/dockerspawner.git`) and switched to  `allowed_images`, but I'm still only getting default spawns. Why might this be?

**Comment by efagerberg** [comment] 2020-07-27 19:54
I have not tried master but I tried 0.11.1 with the allowed_images option and also only get the default image with no form. In my case I do not specify `c.DockerSpawner.image` at all so it seems like `allowed_images` is being looked and just taking the first image.

**Comment by GeorgianaElena** [comment] 2020-08-12 09:04
I didn't manage to reproduce this with:
- `jupyterhub 1.1.0`
- `dockerspawner 0.12.0.dev0 (master)`

and @zi-dan's config:
```python
c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'
c.DockerSpawner.allowed_images = {
    'Jupyteo All-In-One': 'jupytepide/user-spawn-notebook:dev',
    'Jupyteo EO Processing': 'jupytepide/eodata-notebook:1.3.6'
}
```
:confused: 
![bug-not-reproducing](https://user-images.githubusercontent.com/7579677/89995736-8e5cbe00-dc92-11ea-8f7b-2115639dca3e.gif)

**Comment by efagerberg** [comment] 2020-08-12 13:57
So seems like it is on 0.12.0.dev0 did not see that in pypi thanks

**Comment by zi-dan** [comment] 2020-08-12 14:27
I suppose that `c.SwarmSpawner.image` overwrite `c.SwarmSpawner.image_whitelist` so if you remove `c.SwarmSpawner.image` parameter from your config (as @GeorgianaElena write) a list will be displayed without any problems. One trick should be done - first entry in `c.SwarmSpawner.image_whitelist` will be default option displayed on start.

**Comment by mathematicalmichael** [comment] 2020-08-12 18:44
I couldn't get the spawner options working with upgrades, so I'm still using `image_whitelist` with an old docker image for the hub component, if anyone need a stable solution for the time being: `docker pull mathematicalmichael/math-hub`, I have not been able to upgrade the hub + dockerspawner + get the list working all together. it doesn't help that my deployment (jupyterhub-deploy-docker) hasn't been updated to refer to.

**Comment by benz0li** [comment] 2020-10-13 10:58
In my case (SwarmSpawner), `dockerspawner 0.12.0.dev0 (master)` is working with both `jupyterhub 1.0.0` and `jupyterhub 1.1.0` but not `jupyterhub 1.2.0 (master)`.

With `jupyterhub 1.2.0 (master)` the _Spawner Options_ screen does not show up and the default image is used.

**Comment by minrk** [comment] 2020-12-09 10:37
Can folks share the exact commits or releases of jupyterhub and dockerspawner they are working with, as well as the traitlets and Python versions, and relevant sections of jupyterhub_config.py?

I've at least verified that this *does not* affect current master (9ccedbe296321f3dcc33a1c4274dfcd09e690361) of DockerSpawner (and current stable (1.2.2) or development jupyterhub/jupyterhub@ffed8f67a04ad03c08efc5f3290229fc6805d54e) with this config:

```python
# dummy auth for testing
c.JupyterHub.authenticator_class = "dummy"

c.JupyterHub.hub_bind_url = 'http://0.0.0.0:8081'
c.JupyterHub.spawner_class = "docker"
c.DockerSpawner.allowed_images = {
    "data8": "jupyterhub/singleuser:1.0",
    "ds100": "jupyter/base-notebook",
    "cs267": "jupyter/scipy-notebook",
}
c.DockerSpawner.remove = True
```

I have traitlets 5.0.5

**Comment by mathematicalmichael** [comment] 2020-12-21 20:57
do you think this could be explained by the commit 
[988b546](https://github.com/slemonide/dockerspawner/commit/988b546a0d3cd034527fc8c99a797c53afb4f58a) referenced above? seems like a small but significant change with syntax

**Comment by manics** [comment] 2020-12-21 21:03
@mathematicalmichael the name of the function _shouldn't_ matter, the decorator `@default('options_form')` indicates the variable it applies to. That said it might be a bug somewhere, which is why having your full list of component versions would be useful.

**Comment by mathematicalmichael** [comment] 2020-12-21 21:06
@manics thanks, I poked around the open PR's in this repo and found that, deleted my comment shortly thereafter.
I'll take a look at my versions when I have access to that machine / have time to re-try with latest versions. I am hoping this was just an unfortunate consequence of when I chose to test out upgrading.

**Comment by minrk** [comment] 2021-02-26 12:24
I'm going to close this one since the latest comments and testing susgget that 

If someone can rep

**Comment by minrk** [comment] 2021-02-26 12:27
I'm going to close this one since the latest comments and testing suggest that it's working with current versions of everything.

If someone can reproduce this *with* a jupyterhub_config.py and exact, current versions of jupyterhub and dockerspawner, please feel free to open a new Issue with that information and we'll track it down. Things are getting a little mixed up by how old this issue is, since the original report is about a feature not available in an old version, which is fixed by updating dockerspawner.

**Closed by minrk** 2021-02-26 12:27 UTC

**Comment by mathematicalmichael** [comment] 2021-03-19 15:19
I rebuilt my hub / images recently and was able to get the dropdown lists working again.
didn't pin a version of the spawner, so whatever was latest recently (2-3 weeks ago) is definitely working. hub == 1.3.0

sorry I didn't come back around and update the issue. thanks for your help as always, @minrk
