### ISSUE TITLE
Request: Force pull image?

### ISSUE THREAD

**Issue by Spritekin** [jupyterhub/dockerspawner#165] opened 2017-06-27 06:26 UTC
Hi,
I have my jupyter notebook docker image that inherits from jupyterhub/singleuser:latest called uptick-notebook.

So, sometime we might add some custom libraries to the image and release a new uptick-notebook. The new uptick-notebook image then becomes "latest" as uptick-notebook:latest

So my jupyterhub is configured to use:
--DockerSpawner.container_image=cmcrc/uptick-notebook:latest

However as the latest image tag already exists in the server then it will use it by default so my new image is not pulled.

My current workaround is to update my configuration (AWS Cloudformation) to the new image tag (not "latest") so that the new image is selected. Like:
--DockerSpawner.container_image=cmcrc/uptick-notebook:20170627154908

So my question is, would it be possible to add a force pull image to the command so the new image is pulled again? As all the layers exist the time to pull the missing layers would be minimal.

Thanks,
Guimo

**Comment by willingc** [comment] 2017-07-16 18:21
Hi. I'm closing this issue as a duplicate of #121.

**Closed by willingc** 2017-07-16 18:21 UTC
Labels: question
