### ISSUE TITLE
Use runtime nvidia

### ISSUE THREAD

**Issue by Luke035** [jupyterhub/dockerspawner#244] opened 2018-07-12 16:10 UTC
Hi all,

I'm trying to use docker spawner with runtime nvidia set in order attach GPUs installed on my JUPYTERHUB server. 

I tried with the following snippet in my jupyterhub_config.py file but I was unlucky until now. 

`c.DockerSpawner.extra_create_kwargs.update({ 'runtime': 'nvidia' })`

Can you help me understand how to set it up properly?

Thanks.

**Comment by blacksailer** [comment] 2018-07-15 19:41
This happens to me too

**Comment by blacksailer** [comment] 2018-07-15 19:57
Well, current workaround which I found is to set ```"default-runtime":"nvidia"``` in ```\etc\docker\daemon.json```

**Comment by co60ca** [comment] 2018-07-17 13:34
@Luke035 let me know if you still need the Dockerfile for the Nvidia setup as I've already done the work. But I need to prune it down.

**Comment by Luke035** [comment] 2018-07-17 14:24
Hi @co60ca , 
I've managed to define my Dockerfile starting from the one I've linked before, thanks anyway!

Any plan for direct support inside dockerspawner? Do you think is this related to docker python library?

**Comment by co60ca** [comment] 2018-07-17 14:43
I'm not a maintainer but I believe if they wanted to support that they would just have an official image that pulls in the Nvidia files as a part of its build. It might look something like this. I added extra stuff that shows how to make Jupyter Kernels in the Dockerfile too and do GPU allocation with Docker if you are using GPUs like node-generic-resources.
```
from jupyterhub/singleuser:0.9

# NVIDIA garbage taken from the official Dockerfiles for Nvidia.
USER root

# 9.0-base
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates apt-transport-https gnupg-curl && \
    rm -rf /var/lib/apt/lists/* && \
    NVIDIA_GPGKEY_SUM=d1be581509378368edeec8c1eb2958702feedf3bc3d17011adbf24efacce4ab5 && \
    NVIDIA_GPGKEY_FPR=ae09fe4bbd223a84b2ccfce3f60f4b3d7fa2af80 && \
    apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub && \
    apt-key adv --export --no-emit-version -a $NVIDIA_GPGKEY_FPR | tail -n +5 > cudasign.pub && \
    echo "$NVIDIA_GPGKEY_SUM  cudasign.pub" | sha256sum -c --strict - && rm cudasign.pub && \
    echo "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64 /" > /etc/apt/sources.list.d/cuda.list && \
    echo "deb https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64 /" > /etc/apt/sources.list.d/nvidia-ml.list

ENV CUDA_VERSION 9.0.176

ENV CUDA_PKG_VERSION 9-0=$CUDA_VERSION-1
RUN apt-get update && apt-get install -y --no-install-recommends \
        cuda-cudart-$CUDA_PKG_VERSION && \
    ln -s cuda-9.0 /usr/local/cuda && \
    rm -rf /var/lib/apt/lists/*

# nvidia-docker 1.0
LABEL com.nvidia.volumes.needed="nvidia_driver"
LABEL com.nvidia.cuda.version="${CUDA_VERSION}"

RUN echo "/usr/local/nvidia/lib" >> /etc/ld.so.conf.d/nvidia.conf && \
    echo "/usr/local/nvidia/lib64" >> /etc/ld.so.conf.d/nvidia.conf

ENV PATH /usr/local/nvidia/bin:/usr/local/cuda/bin:${PATH}
ENV LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64

# nvidia-container-runtime
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility
ENV NVIDIA_REQUIRE_CUDA "cuda>=9.0"

# 9.0-runtime
ENV NCCL_VERSION 2.2.12

RUN apt-get update && apt-get install -y --no-install-recommends \
        cuda-libraries-$CUDA_PKG_VERSION \
        cuda-cublas-9-0=9.0.176.3-1 \
        libnccl2=$NCCL_VERSION-1+cuda9.0 && \
    rm -rf /var/lib/apt/lists/*

# 9.0-cudnn7-devel
RUN apt-get update && apt-get install -y --no-install-recommends \
        cuda-libraries-dev-$CUDA_PKG_VERSION \
        cuda-nvml-dev-$CUDA_PKG_VERSION \
        cuda-minimal-build-$CUDA_PKG_VERSION \
        cuda-command-line-tools-$CUDA_PKG_VERSION \
        cuda-core-9-0=9.0.176.3-1 \
        cuda-cublas-dev-9-0=9.0.176.3-1 \
        libnccl-dev=$NCCL_VERSION-1+cuda9.0 && \
    rm -rf /var/lib/apt/lists/*

ENV LIBRARY_PATH /usr/local/cuda/lib64/stubs

# cudnn7-devel
ENV CUDNN_VERSION 7.1.4.18
LABEL com.nvidia.cudnn.version="${CUDNN_VERSION}"

RUN apt-get update && apt-get install -y --no-install-recommends \
            libcudnn7=$CUDNN_VERSION-1+cuda9.0 \
            libcudnn7-dev=$CUDNN_VERSION-1+cuda9.0 && \
    rm -rf /var/lib/apt/lists/*


# This section is useful if you want to do GPU allocation (not isolation), and assumes you are using
# node-generic-resources to do so
# Add DOCKER_RESOURCE_GPU shim to start-notebook.sh
# This also gives a way to share single GPUs to multiple users if the resource ends up an extra `-`
# When you generate Nvidia generic GPU resources you can multiply them by adding suffixes
# i.e. GPU-c143e771 is the same as GPU-c143e771-2, GPU-c143e771-3 ...

RUN sed -i '6 iexport CUDA_VISIBLE_DEVICES=$(echo $DOCKER_RESOURCE_GPU | cut -d '-' -f 1,2)' /usr/local/bin/start-notebook.sh

# Python Kernel Extras

RUN conda create -n pytorch
RUN ["/bin/bash", "-c", \
	" . activate pytorch && conda install pytorch torchvision cuda91 scipy pandas matplotlib seaborn scikit-learn -c pytorch"]
RUN ["/bin/bash", "-c", ". activate pytorch && pip install ipykernel && python -m ipykernel install --user --display-name \"Python 3 - Pytorch\" --name pytorch"]

```

**Comment by Luke035** [comment] 2018-07-17 16:01
That's a great workaround! Anyway since the dockerd supports multiple runtimes, having the chance to select which runtime to use will be great.

**Comment by minrk** [comment] 2018-08-29 10:08
It is definitely a question for the docker Python API. From [the docs](https://docker-py.readthedocs.io/en/stable/containers.html?highlight=runtime), it looks like your config should do what you are after:

```python
c.DockerSpawner.extra_create_kwargs.update({'runtime', 'nvidia'})
```

If that doesn't work, make sure that your docker Python client is fully up to date, and try creating a container by hand with the docker Python API to see if you can make it work.

**Comment by ltupin** [comment] 2018-08-29 10:37
Just tried (minutes ago lol) not working :-(

**Comment by ltupin** [comment] 2018-08-29 10:38
Python 3.6.5
docker lib 3.5.0

**Comment by ltupin** [comment] 2018-08-29 10:41
Dear people, just to share,

The [wrapspawner.py](https://github.com/jupyterhub/wrapspawner/blob/master/wrapspawner/wrapspawner.py) is for [nvidia-docker1.0](https://github.com/NVIDIA/nvidia-docker/wiki/nvidia-docker-plugin). 

The args bellow are not available for the new version:
```python 
def _nvidia_args(self):
    try:
        resp = urllib.request.urlopen('http://localhost:3476/v1.0/docker/cli/json')
        body = resp.read().decode('utf-8')
        args =  json.loads(body)
        return dict(
            read_only_volumes={vol.split(':')[0]: vol.split(':')[1] for vol in args['Volumes']},
            extra_create_kwargs={"volume_driver": args['VolumeDriver']},
            extra_host_config={"devices": args['Devices']},
        )
    except urllib.error.URLError:
        return {}


def _docker_profile(self, nvidia_args, image):
    spawner_args = dict(container_image=image, network_name=self.user.name)
    spawner_args.update(self.docker_spawner_args)
    spawner_args.update(nvidia_args)
    nvidia_enabled = "w/GPU" if len(nvidia_args) > 0 else "no GPU"
    return ("Docker: (%s): %s"%(nvidia_enabled, image), "docker-%s"%(image), "dockerspawner.SystemUserSpawner", spawner_args)
```

Unfortunately, nvidia still not provide a new API for nvidia-docker2.0 :-( --> https://github.com/NVIDIA/nvidia-docker/issues/563.

Can I have your confirmation that your workaround is working when you spawn a container from **jupyterhub** with **nvidia-docker2.0** @co60ca ? 
I assume it cannot be.

Any news regarding the nvidia-docker2.0 API @flx42 please ?

Just fyi, as our notebook docker images as a **lot of customization**, instead of starting FROM jupyterhub/singleuser:0.9 I prefered the opposite way starting from nvidia and add my notebook stuffs. More precisely, I used the tensorflowGPU container who is using the nvidia one. I think that will be easier to maintain (that's my point of view). Here the links:

TenSorflowGPU dockerfile: 
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docker/Dockerfile.gpu
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/dockerfiles/dockerfiles/nvidia.Dockerfile
(be carefull there are changing the organization)
Repository:
https://hub.docker.com/r/tensorflow/tensorflow/

Nvidia-CUDA 9.0 dockerfile:
https://gitlab.com/nvidia/cuda/blob/ubuntu16.04/9.0/base/Dockerfile
Repository:
https://hub.docker.com/r/nvidia/cuda/

**Comment by ltupin** [comment] 2018-08-29 10:45
The strange things is that runtime still exist in docker-py:
https://docker-py.readthedocs.io/en/stable/containers.html#

**Comment by ltupin** [comment] 2018-08-29 10:59
If I look at docker logs everything seems fine and runtime nvidia is send :-(

```
Aug 29 12:53:14 hostname dockerd[9097]: time="2018-08-29T06:53:14.851806971-04:00" level=debug msg="form data: {\"AttachStderr\":true,\"AttachStdin\":false,\"AttachStdout\":true,\"Cmd\":[\"/usr/local/bin/start-notebook.sh\"],\"Env\":[\"GRANT_SUDO=1\",\"JUPYTERHUB_ADMIN_ACCESS=1\",\"UID=0\",\"GUID=0\",\"NB_UID=0\",\"NB_GUID=0\",\"NB_USER=root\",\"JUPYTERHUB_API_TOKEN=0c6f591c350444ffab0dc5194axxxxxx\",\"JPY_API_TOKEN=0c6f591c350444ffab0dc5194axxxxxx\",\"JUPYTERHUB_CLIENT_ID=jupyterhub-user-test\",\"JUPYTERHUB_HOST=\",\"JUPYTERHUB_OAUTH_CALLBACK_URL=/user/test/oauth_callback\",\"JUPYTERHUB_USER=test\",\"JUPYTERHUB_API_URL=http://jupyterhub:8080/hub/api\",\"JUPYTERHUB_BASE_URL=/\",\"JUPYTERHUB_SERVICE_PREFIX=/user/test/\"],\"ExposedPorts\":{\"8888/tcp\":null},\"HostConfig\":{\"Binds\":[\"jupyterhub-user-test:/home/test:rw\"],\"Links\":[],\"NetworkMode\":\"jupyterhub-network\"},\"Image\":\"jupyterhub-notebook-gpu:stable\",\"NetworkDisabled\":false,\"OpenStdin\":false,\"Runtime\":\"nvidia\",\"StdinOnce\":false,\"Tty\":false,\"Volumes\":{\"/home/test\":{}}}"
```
but if I inspect I can confirm it use runc runtime
```
docker inspect jupyter-test | grep Runtime
            "Runtime": "runc",
            "CpuRealtimeRuntime": 0,
```

It looks like the docker-py is not working

**Comment by ltupin** [comment] 2018-08-29 13:37
Dear people,

I can confirm that with:
```python
c.DockerSpawner.image = 'yourimage'
c.DockerSpawner.extra_create_kwargs = {'runtime': 'nvidia'}
c.DockerSpawner.extra_host_config = {'runtime': 'nvidia'}
```
Thanks to @minrk for is support on gitter :-D

**Comment by minrk** [comment] 2018-09-03 15:57
Following up on that, the `extra_create_kwargs` is unnecessary. Only the `extra_host_config` is required. The main source of confusion was that the docker Python docs suggest that you can specify `runtime` via `create`, but this is only true if there is *not* a host_config also specified. Since DockerSpawner always specifies a host config, runtime can only be specified there.

**Comment by vilhelmen** [comment] 2018-10-23 19:12
Unfortunately, this doesn't appear to work with the swarm spawner. I'm attempting to reverse engineer it from the docker.py source, but it seems that the runtime can only be specified to calls to create_container and create_host_config, but the swarm spawner uses create_service. If someone happens to know, I'd appreciate the advice.

I'll update if I find anything. Push comes to shove, the docker configuration file (`/etc/docker/daemon.json`, `"default-runtime": "nvidia"`) can set the runtime to the nvidia runtime on the GPU node and forbid non-gpu containers from the node via constraints.

For those looking to add an Nvidia-enabled node to their swarm, I'm labeling the node as a GPU node (`docker node update --label-add gpu=yes gpu.node.host.domain`) and using the wrapper spawner to set the label constraint to the gpu-enabled node.

```
c.ProfilesSpawner.profiles = [
    ('Swarm GPU', 'swarm-gpu', 'dockerspawner.SwarmSpawner', {
            'image': 'tensorflow/tensorflow:1.11.0-gpu',
            'extra_task_spec': {
                'placement': ['node.labels.gpu==yes'],
            },
        })]
```

**Comment by cyliu0204** [comment] 2019-06-04 10:13
Hi @co60ca @Luke035  ,
 I've managed to define my own Dockerfile to use gpu in Jupyterhub, but failed thousands of times, can u two post your Dockerfile here fore reference? thanks

**Comment by Luke035** [comment] 2019-06-05 09:30
Hi @cyliu0204, 

unfortunately I don't have the Dockerfile anymore and I can't retrieve it. 
As far as I remember the main problem was to "rewrite" the [single user base dockerfile](https://github.com/jupyter/docker-stacks/tree/master/base-notebook) using as image a CUDA compatible image instead of the standard one. 

I think you can literally copy the Dockerfile, change the from directive with a CUDA compatible image, and rebuild the container. 

Hope this helps.

**Comment by cyliu0204** [comment] 2019-06-06 11:06
> Hi @cyliu0204,
> 
> unfortunately I don't have the Dockerfile anymore and I can't retrieve it.
> As far as I remember the main problem was to "rewrite" the [single user base dockerfile](https://github.com/jupyter/docker-stacks/tree/master/base-notebook) using as image a CUDA compatible image instead of the standard one.
> 
> I think you can literally copy the Dockerfile, change the from directive with a CUDA compatible image, and rebuild the container.
> 
> Hope this helps.

Really appreciate for your advice, I have built a successfully running image based on nvidia CUDA image.

Seemingly I can't get the CUDA's Dockerfile, so I built the image based on it.

thanks anyway;

**Comment by jamesdbrock** [comment] 2019-08-27 00:45
With Docker 18, it was possible to make `DockerSpawner` spawn images with `nvidia-docker2` by just setting the [Docker system-wide `"default-runtime": "nvidia"`](https://github.com/NVIDIA/nvidia-container-runtime#docker-engine-setup).

With Docker 19, Nvidia support is now built into Docker and there is no separate "nvidia runtime," instead we are supposed to use a command line argument to enable Nvidia, like: `docker run --gpus all`.

How can I make `DockerSpawner` spawn images with Nvidia runtime support in Docker 19? 

This, for example, does not work:

```
c.DockerSpawner.extra_host_config = { '--gpus': 'all', }
```

and will result in this error:

```
Error: __init__() got an unexpected keyword argument '--gpus'
```

References:

https://github.com/moby/moby/pull/38828

https://github.com/docker/cli/pull/1714

**Comment by jamesdbrock** [comment] 2019-08-27 00:55
I guess basically we're only allowed to pass `docker run` arguments which are specifically named by the `docker-py` `HostConfig` constructor? https://github.com/docker/docker-py/blob/1c36417d8feb523dd2c6c5fe57c65388ad6e6a01/docker/types/containers.py#L157

**Comment by jamesdbrock** [comment] 2019-08-27 01:07
Here's the `docker-py` issue requesting support for `docker run --gpus`: https://github.com/docker/docker-py/issues/2395

No pull requests yet.

**Comment by ManuelRaddatz** [comment] 2020-02-16 12:45
Hi there,

are there any news or updates regarding this issue?

On the docker host I can run:
`docker run --gpus 2 nvidia/cuda:9.0-base nvidia-smi`

successfully but I can not get this work with jupyterhub

**Comment by AnubhavUjjawal** [comment] 2021-02-25 06:09
Ok, I found a workaround. Just inherit the `DockerSpawner` to create your own spawner, and override `create_object` method like this:

```python
@gen.coroutine
def create_object(self):
    """Create the container/service object"""

    create_kwargs = dict(
        image=self.image,
        environment=self.get_env(),
        volumes=self.volume_mount_points,
        name=self.container_name,
        command=(yield self.get_command()),
    )

    # ensure internal port is exposed
    create_kwargs["ports"] = {"%i/tcp" % self.port: None}

    create_kwargs.update(self.extra_create_kwargs)

    # build the dictionary of keyword arguments for host_config
    host_config = dict(binds=self.volume_binds, links=self.links)

    if getattr(self, "mem_limit", None) is not None:
        # If jupyterhub version > 0.7, mem_limit is a traitlet that can
        # be directly configured. If so, use it to set mem_limit.
        # this will still be overriden by extra_host_config
        host_config["mem_limit"] = self.mem_limit

    if not self.use_internal_ip:
        host_config["port_bindings"] = {self.port: (self.host_ip,)}
    host_config.update(self.extra_host_config)
    host_config.setdefault("network_mode", self.network_name)
    if IS_GPU:
        host_config.update(device_requests=[
            docker.types.DeviceRequest(count=-1, capabilities=[['gpu']])
        ])
    self.log.debug("Starting host with config: %s", host_config)

    host_config = self.client.create_host_config(**host_config)

    create_kwargs.setdefault("host_config", {}).update(host_config)

    # create the container
    obj = yield self.docker("create_container", **create_kwargs)
    return obj
```


Notice the condition `if IS_GPU`. IS_GPU can be configured through any appropriate mechanism such as env variables. If you don't want to allocate all GPUs, you can add extra logic here for selecting GPUs.

Reference: https://github.com/docker/docker-py/pull/2471

@minrk Would you like a PR for this functionality?

**Comment by minrk** [comment] 2021-02-25 12:40
Thanks for the working example! I'm not sure what a PR would include, though. From the looks of what you have there, it seems like `extra_host_config` is already enough:

```python
import docker

c.DockerSpawner.extra_host_config = {
    "device_requests": [
        docker.types.DeviceRequest(
            count=-1,
            capabilities=[["gpu"]],
        ),
    ],
}
```

which seems to work when I try it, so we already have this feature satisfied by passing through arguments to docker-py.

**Comment by AnubhavUjjawal** [comment] 2021-02-25 13:06
Oh, that's better then! 😄

**Comment by minrk** [comment] 2021-02-26 09:49
Great! Then I'll close this as resolved with that config as the example.

**Closed by minrk** 2021-02-26 09:49 UTC
