### ISSUE TITLE
Notebook has jupyterhub version 0.8.1, but the Hub expects 1.0.0.dev. Try installing jupyterhub==1.0.0.dev in the user environment

### ISSUE THREAD

**Issue by yfc845** [jupyterhub/dockerspawner#251] opened 2018-08-13 01:48 UTC
Hi supporter,

We are trying to upgrade our jupyterhub to 1.0.0 but it complains about:
Notebook has jupyterhub version 0.8.1, but the Hub expects 1.0.0.dev. Try installing jupyterhub==1.0.0.dev in the user environment 

When will we have a jupyterhub/singleuser:1.0.0 image ready? Is there a plan?

**Comment by maroshmka** [comment] 2019-07-31 07:47
same issue for us. error:

> Redirect loop detected. Notebook has jupyterhub version 1.0.0, but the Hub expects 0.9.6. Try installing jupyterhub==0.9.6 in the user environment if you continue to have problems.

**Comment by jtlz2** [comment] 2019-11-18 14:07
Any fix for this? I tried reinstalling but same problem

**Comment by ArtemChekunov** [comment] 2019-11-26 12:16
I believe the problem is here: https://github.com/jupyterhub/dockerspawner/blob/b2a6ef16a79be4fb0e65ac2446f0d496637c137f/dockerspawner/dockerspawner.py#L37

It is pick up a <major>.<minor> version for container_image https://github.com/jupyterhub/dockerspawner/blob/b2a6ef16a79be4fb0e65ac2446f0d496637c137f/dockerspawner/dockerspawner.py#L153

but later it does compare <major>.<minor>.<patch> which are not equal

@jcrist you can use a workaround
in the config file, you can specify exactly the same image which you are using got hub itself.
```
c.DockerSpawner.image = 'jupyterhub/jupyterhub:1.0.0'

```

**Comment by minrk** [comment] 2021-03-12 08:58
Hi! I’m going through and cleaning up old/stale issues on this repo. Sorry for not responding in a reasonable amount of time!

There are tagged images for all recent jupyterhub releases.

The major.minor truncation in the image tag is not relevant to the comparison, which uses the full version of both notebook server and hub.

**Closed by minrk** 2021-03-12 08:58 UTC
