### ISSUE TITLE
CPU limit failed

### ISSUE THREAD

**Issue by LinG955** [jupyterhub/dockerspawner#430] opened 2021-07-06 08:38 UTC
### Bug description

I set cpu limit in the jupyterhub_config.py: 
```python
c.DockerSpawner.cpu_limit = 0.5
```
However, each single-user notebook server still can use a CPU. 
**one user:**
![1](https://user-images.githubusercontent.com/36889092/124565876-12a0cc80-de75-11eb-8666-ff40b356ebb6.png)
**two user:**
![2](https://user-images.githubusercontent.com/36889092/124566596-c73aee00-de75-11eb-848d-f8c6393c8c9a.png)

it is no problem to test CPU limit using other image: 
```bash
sudo docker run -it --rm --cpus=0.5 jiuchen1986/u-stress /bin/bash

stress -c 4
```
![stress-0 5](https://user-images.githubusercontent.com/36889092/124568942-1124d380-de78-11eb-9dfa-5c49606dce4b.png)

### How to reproduce

```bash
docker pull ling955/hub:latest

sudo docker run --rm -it \
  -v /var/run/docker.sock:/var/run/docker.sock \
  --net jupyterhub \
  --name jupyterhub \
  -p 9500:8000 \
  -d \
  ling955/hub:latest
```

### Your personal set up

 - OS: CentOS 7
 
- jupyterhub_config.py
```python
# jupyterhub_config.py

c.JupyterHub.authenticator_class = 'firstuseauthenticator.FirstUseAuthenticator'

c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'

c.JupyterHub.hub_ip = '0.0.0.0'

c.JupyterHub.hub_ip = 'jupyterhub'

c.DockerSpawner.image = 'ling955/gpu-jupyter:cuda10.1-v01'

import docker
c.DockerSpawner.extra_host_config = {
    "device_requests": [
        docker.types.DeviceRequest(
            count=-1,
            capabilities=[["gpu"]],
        ),
    ],
}

c.DockerSpawner.mem_limit = '64G'
c.DockerSpawner.cpu_limit = 0.5

c.Spawner.default_url = '/user/%U/lab'

c.DockerSpawner.network_name = 'jupyterhub'

c.DockerSpawner.remove = True

import os
notebook_dir = os.environ.get('DOCKER_NOTEBOOK_DIR') or '/home/jovyan/work'
c.DockerSpawner.notebook_dir = notebook_dir

c.DockerSpawner.volumes = {
    'jupyterhub-user-{username}': notebook_dir,
    "/home/ioc/data": {
        "bind": "/home/jovyan/work/common",
        "mode": "ro",
    }
}
```

**Comment by minrk** [comment] 2021-07-16 12:02
closing as duplicate of #428, should be fixed by #435

**Closed by minrk** 2021-07-16 12:02 UTC
Labels: bug
